version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    container_name: front
    volumes:
      - .:/usr/src/app
    restart: always

networks:
  mynetwork:
